name: mesorch
channels:
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2025.9.9=h06a4308_0
  - ld_impl_linux-64=2.40=h12ee557_0
  - libffi=3.3=he6710b0_2
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - libuuid=1.41.5=h5eee18b_0
  - libxcb=1.17.0=h9b100fa_0
  - libzlib=1.3.1=hb25bd0a_0
  - ncurses=6.5=h7934f7d_0
  - openssl=1.1.1w=h7f8727e_0
  - pip=25.2=pyhc872135_0
  - pthread-stubs=0.3=h0ce48e5_1
  - python=3.10.0=h12debd9_5
  - readline=8.3=hc2a1206_0
  - setuptools=78.1.1=py310h06a4308_0
  - sqlite=3.50.2=hb25bd0a_1
  - tk=8.6.15=h54e0aa7_0
  - tzdata=2025b=h04d1e81_0
  - wheel=0.45.1=py310h06a4308_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - zlib=1.3.1=hb25bd0a_0
  - pip:
      - absl-py==2.3.1
      - albumentations==1.3.0
      - appdirs==1.4.4
      - certifi==2025.8.3
      - charset-normalizer==3.4.3
      - colorama==0.4.6
      - contourpy==1.3.2
      - cycler==0.12.1
      - easydict==1.13
      - einops==0.8.1
      - filelock==3.20.0
      - fonttools==4.60.1
      - fsspec==2025.9.0
      - fvcore==0.1.5.post20221221
      - grad-cam==1.5.5
      - grpcio==1.75.1
      - hf-xet==1.1.10
      - huggingface-hub==0.35.3
      - idna==3.10
      - imageio==2.37.0
      - imdlbenco==0.1.42
      - imgaug==0.4.0
      - iopath==0.1.10
      - jinja2==3.1.6
      - joblib==1.5.2
      - kiwisolver==1.4.9
      - lazy-loader==0.4
      - mamba-ssm==2.2.6.post2
      - mambavision==1.2.0
      - markdown==3.9
      - markdown-it-py==4.0.0
      - markupsafe==3.0.3
      - matplotlib==3.10.7
      - mdurl==0.1.2
      - mpmath==1.3.0
      - natten==0.21.0+torch270cu128
      - networkx==3.4.2
      - ninja==1.13.0
      - numpy==1.26.4
      - nvidia-cublas-cu12==12.4.5.8
      - nvidia-cuda-cupti-cu12==12.4.127
      - nvidia-cuda-nvrtc-cu12==12.4.127
      - nvidia-cuda-runtime-cu12==12.4.127
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.2.1.3
      - nvidia-cufile-cu12==1.13.1.3
      - nvidia-curand-cu12==10.3.5.147
      - nvidia-cusolver-cu12==11.6.1.9
      - nvidia-cusparse-cu12==12.3.1.170
      - nvidia-cusparselt-cu12==0.7.1
      - nvidia-nccl-cu12==2.21.5
      - nvidia-nvjitlink-cu12==12.4.127
      - nvidia-nvshmem-cu12==3.3.20
      - nvidia-nvtx-cu12==12.4.127
      - opencv-python==4.12.0.88
      - opencv-python-headless==4.11.0.86
      - packaging==25.0
      - pillow==11.3.0
      - portalocker==3.2.0
      - prettytable==3.16.0
      - protobuf==6.32.1
      - pygments==2.19.2
      - pyparsing==3.2.5
      - python-dateutil==2.9.0.post0
      - pyturbojpeg==1.8.2
      - pyyaml==6.0.3
      - qudida==0.0.4
      - regex==2025.9.18
      - requests==2.32.5
      - rich==14.1.0
      - safetensors==0.6.2
      - scikit-image==0.25.2
      - scikit-learn==1.7.2
      - scipy==1.15.3
      - shapely==2.1.2
      - six==1.17.0
      - sympy==1.13.1
      - tabulate==0.9.0
      - tensorboard==2.20.0
      - tensorboard-data-server==0.7.2
      - termcolor==3.2.0
      - threadpoolctl==3.6.0
      - tifffile==2025.5.10
      - timm==1.0.20
      - tokenizers==0.22.1
      - torch==2.5.1
      - torchaudio==2.5.1+cu121
      - torchvision==0.20.1+cu121
      - tqdm==4.67.1
      - transformers==4.57.1
      - triton==3.1.0
      - ttach==0.0.3
      - typing-extensions==4.15.0
      - urllib3==2.5.0
      - wcwidth==0.2.14
      - werkzeug==3.1.3
      - yacs==0.1.8
prefix: /data/jdon492/anaconda3/envs/mesorch
